// Single source of truth for how a project's background is resolved to a real
// URL. `video_settings.background` is stored as a STRING with one of three
// shapes: a preset key (an id in BACKGROUND_PRESETS), a saved background
// reference ("saved-<uuid>", looked up in the `backgrounds` table), or a
// generated reference ("generated-<index>" into video_settings.customBackgrounds).
// Both the client wizard (generate-step) and the server (/api/video/record)
// must resolve identically — hence this shared module.

export const DEFAULT_BACKGROUND_URL = "/abstract-background.png"

export type BackgroundCategory = "Scenic" | "Vibrant" | "Ocean" | "Sunset" | "Dark" | "Nature" | "Luxe"

export interface BackgroundPreset {
  id: string // value stored in video_settings.background
  name: string
  url: string
  category: BackgroundCategory
}

// The pre-made background library shown in the wizard. Gradient assets are
// generated by scripts/generate-backgrounds.mjs into public/backgrounds/.
export const BACKGROUND_PRESETS: BackgroundPreset[] = [
  { id: "default", name: "Abstract", url: "/abstract-background.png", category: "Scenic" },
  { id: "nature", name: "Mountain Lake", url: "/serene-mountain-lake.png", category: "Scenic" },
  { id: "city", name: "City Skyline", url: "/vibrant-city-skyline.png", category: "Scenic" },
  { id: "space", name: "Space Stars", url: "/space-stars.png", category: "Scenic" },

  { id: "grad-purple-pink", name: "Purple Pink", url: "/backgrounds/grad-purple-pink.png", category: "Vibrant" },
  { id: "grad-blue-violet", name: "Blue Violet", url: "/backgrounds/grad-blue-violet.png", category: "Vibrant" },
  { id: "grad-pink-orange", name: "Pink Orange", url: "/backgrounds/grad-pink-orange.png", category: "Vibrant" },
  { id: "grad-amber-pink", name: "Amber Pink", url: "/backgrounds/grad-amber-pink.png", category: "Vibrant" },
  { id: "grad-violet-cyan", name: "Violet Cyan", url: "/backgrounds/grad-violet-cyan.png", category: "Vibrant" },
  { id: "grad-aurora", name: "Aurora", url: "/backgrounds/grad-aurora.png", category: "Vibrant" },
  { id: "grad-slate-rose", name: "Slate Rose", url: "/backgrounds/grad-slate-rose.png", category: "Vibrant" },

  { id: "grad-ocean-teal", name: "Ocean Teal", url: "/backgrounds/grad-ocean-teal.png", category: "Ocean" },
  { id: "grad-cyan-indigo", name: "Cyan Indigo", url: "/backgrounds/grad-cyan-indigo.png", category: "Ocean" },
  { id: "grad-deep-sea", name: "Deep Sea", url: "/backgrounds/grad-deep-sea.png", category: "Ocean" },
  { id: "grad-mint-teal", name: "Mint Teal", url: "/backgrounds/grad-mint-teal.png", category: "Ocean" },

  { id: "grad-sunset-red", name: "Sunset", url: "/backgrounds/grad-sunset-red.png", category: "Sunset" },
  { id: "grad-golden-hour", name: "Golden Hour", url: "/backgrounds/grad-golden-hour.png", category: "Sunset" },

  { id: "grad-charcoal", name: "Charcoal", url: "/backgrounds/grad-charcoal.png", category: "Dark" },
  { id: "grad-midnight", name: "Midnight", url: "/backgrounds/grad-midnight.png", category: "Dark" },
  { id: "grad-noir", name: "Noir", url: "/backgrounds/grad-noir.png", category: "Dark" },
  { id: "grad-crimson", name: "Crimson", url: "/backgrounds/grad-crimson.png", category: "Dark" },

  { id: "grad-forest", name: "Forest", url: "/backgrounds/grad-forest.png", category: "Nature" },
  { id: "grad-emerald", name: "Emerald", url: "/backgrounds/grad-emerald.png", category: "Nature" },

  { id: "grad-royal-gold", name: "Royal Gold", url: "/backgrounds/grad-royal-gold.png", category: "Luxe" },
]

// Preset id -> URL, derived from the catalog plus legacy aliases so older
// stored values still resolve.
export const PRESET_BACKGROUND_MAP: Record<string, string> = {
  ...Object.fromEntries(BACKGROUND_PRESETS.map((b) => [b.id, b.url])),
  "abstract-gradient": "/abstract-background.png",
  "mountain-lake": "/serene-mountain-lake.png",
  "city-skyline": "/vibrant-city-skyline.png",
  "space-stars": "/space-stars.png",
}

export type BackgroundKind = "saved" | "generated" | "preset"

export interface VideoSettings {
  background?: string
  customBackgrounds?: string[]
  format?: "vertical" | "square" | "horizontal"
  quality?: "720p" | "1080p" | "4k"
  captions?: boolean
  // The wizard stores duration as a Select string ("auto"/"15"/"30"/"60"); the
  // record route coerces it to an integer. Allow both shapes.
  duration?: string | number
  // Ken Burns background animation (default static).
  animation?: "none" | "zoom-in" | "zoom-out" | "pan"
  [key: string]: unknown
}

export function backgroundKindOf(background: string | undefined | null): BackgroundKind {
  if (typeof background === "string" && background.startsWith("saved-")) return "saved"
  if (typeof background === "string" && background.startsWith("generated-")) return "generated"
  return "preset"
}

// Resolve a background string to a concrete URL.
// `lookupSavedUrl(id)` resolves a "saved-<id>" reference against the backgrounds
// table; the caller injects it (client passes a Supabase-backed fn scoped to the
// user; the server route does the same) so this module stays storage-agnostic.
export async function resolveBackgroundUrl(
  videoSettings: VideoSettings | null | undefined,
  lookupSavedUrl?: (id: string) => Promise<string | null>,
): Promise<string> {
  const background = (videoSettings?.background ?? "default").toString()

  if (background.startsWith("saved-")) {
    const savedId = background.slice("saved-".length).trim()
    if (savedId && lookupSavedUrl) {
      try {
        const url = await lookupSavedUrl(savedId)
        if (url && url.trim() !== "") return url
      } catch {
        // fall through to default
      }
    }
    return DEFAULT_BACKGROUND_URL
  }

  if (background.startsWith("generated-")) {
    const indexStr = background.slice("generated-".length)
    const index = Number.parseInt(indexStr, 10)
    if (!Number.isNaN(index)) {
      const url = videoSettings?.customBackgrounds?.[index]
      if (url && url.trim() !== "") return url
    }
    return DEFAULT_BACKGROUND_URL
  }

  return PRESET_BACKGROUND_MAP[background] || DEFAULT_BACKGROUND_URL
}
